version: '2'
services:
  auth-service:
    build: ./auth-service
    restart: always
    volumes:
      - ./auth-service/log:/log
    depends_on:
      - db
    env_file:
      - backend.env
    networks:
      - backend-network
      
  customer-service:
    build: ./customer-service
    restart: always
    volumes:
      - ./customer-service/log:/log
    depends_on:
      - db
    env_file:
      - backend.env
    networks:
      - backend-network
      
  employee-service:
    build: ./employee-service
    restart: always
    volumes:
      - ./employee-service/log:/log
    depends_on:
      - db
    env_file:
      - backend.env
    networks:
      - backend-network
      
  inventory-service:
    build: ./inventory-service
    restart: always
    volumes:
      - ./inventory-service/log:/log
    depends_on:
      - db
    env_file:
      - backend.env
    networks:
      - backend-network
      
  report-service:
    build: ./report-service
    restart: always
    volumes:
      - ./report-service/log:/log
    depends_on:
      - db
    env_file:
      - backend.env
    networks:
      - backend-network
      
  schedule-service:
    build: ./schedule-service
    restart: always
    volumes:
      - ./schedule-service/log:/log
    depends_on:
      - db
    env_file:
      - backend.env
    networks:
      - backend-network
      
  storage-service:
    build: ./storage-service
    restart: always
    volumes:
      - ./storage-service/log:/log
    depends_on:
      - db
    env_file:
      - backend.env
    networks:
      - backend-network
      
  frontend-service:
    build: ./frontend-service
    restart: always
    volumes:
      - ./frontend-service/log:/log
    depends_on:
      - auth-service
      - customer-service
      - employee-service
      - inventory-service
      - report-service
      - schedule-service
      - storage-service
    networks:
      - frontend-network

  nginx:
    build: ./nginx
    restart: always
    networks:
      - frontend-network
      - backend-network
    ports:
      - "9000:80"
    depends_on:
      - frontend-service
      
  db:
    image: mariadb:10.4.24
    restart: always
    env_file:
      - db.env
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:
